version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloudbanking-db
    environment:
      POSTGRES_DB: cloudbanking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloudbanking-net

  app:
    build: .
    container_name: cloudbanking-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloudbanking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - cloudbanking-net

volumes:
  pgdata:

networks:
  cloudbanking-net:
